### ISSUE TITLE
libreoffice recipes are too outdated

### ISSUE THREAD

**Issue by clopez** [schnitzeltony/meta-office#6]
This layer has recipes for libreoffice 5.0.6.

But upstream libreoffice 5.x is already at 5.4.7

**Comment by megastallman** [comment]
I agree with you @clopez 
There is no reason to continue supporting v5 because the 6-th version is in upstream. You can see https://github.com/schnitzeltony/meta-office/issues/8 where I can't build clucene.
I wish I could refactor the recipe to move it to v6, but I've stuck with some unknown errors. Maybe I should try it and post my step-by-step results here?

**Comment by schnitzeltony** [comment]
Now we are at 6.2.6.1
